### ISSUE TITLE
Example not reproducible: img_width not found

### ISSUE THREAD

**Issue by JosiahParry** [ropensci/terrainr#68]
I suspect this is a change that came with the newest version of {sf}. The examples in get_tiles() does not work out of the box. 
 
```r
library(terrainr)
simulated_data <- data.frame(
  id = seq(1, 100, 1),
  lat = runif(100, 44.04905, 44.17609),
  lng = runif(100, -74.01188, -73.83493)
)

simulated_data <- sf::st_as_sf(simulated_data, coords = c("lng", "lat"))

get_tiles(simulated_data, tempfile())
```
```
Error in hit_national_map_api(current_bbox, current_box[["img_width"]],  : 
  object '"img_width"' not found
In addition: Warning messages:
1: Assuming geographic CRS.
ℹ Set 'projected' to TRUE if projected. 
2: Assuming CRS of EPSG 4326
ℹ Set bboxSR explicity to override 
```

**Comment by mikemahoney218** [comment]
Thanks for the report! I'm unfortunately not going to be able to dig into this until Tuesday, but hopefully will be able to get a patch in after that.

**Comment by mikemahoney218** [comment]
Kinda dissatisfying resolution, but the basic issue is that the API was down a few weeks ago, and now it's back up. The example no longer errors (but I reproduced it at the time and this API is known for being flaky).

This error message should be nicer, but I'm going to close out the issue for the moment because I'm not currently actively working on terrainr, so that would need to happen as part of a larger overhaul effort (which I don't have scheduled).

Josiah -- if terrainr's tests being flaky are blocking you on something, let me know and we can find a workaround. 

But if you were looking for a better way to download this data, might I recommend the [rsi package](https://permian-global-research.github.io/rsi/), which has a nicer interface, _much_ faster download times, and is overall an upgrade from terrainr:
```
rsi::get_dem(
  some_aoi,
  "2010-01-01",
  "2024-01-01",
  asset_names = rsi::dem_band_mapping$planetary_computer_v1$`3dep-seamless`
)
```
